version: '{build}'

build:
    verbosity: detailed

branches:
    only:
        - master

image: Visual Studio 2015

environment:
    matrix:
        - APPVEYOR_SAVE_CACHE_ON_ERROR: true
          DLL_PATH: lib\Release\fec.dll

install:
    - call "%APPVEYOR_BUILD_FOLDER%\\.appveyor-install-tools.cmd"

before_build:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
    - cd %APPVEYOR_BUILD_FOLDER%

build_script:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015" -A Win32 -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --config Release --target shim
    - cmake --build . --config Release --target test_runners
    - dumpbin /EXPORTS %DLL_PATH%

test_script:
    - cd tests
    - set CTEST_OUTPUT_ON_FAILURE=1
    - ctest -C Release

cache:
    - C:\projects\tools\ninja
    - C:\projects\tools\llvm-installer.exe
